//
//  CountProductsInteractor.swift
//  Groceries
//
//  Created by Juan Giannuzzo on 2/15/17.
//  Copyright (c) 2017 me. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CountProductsInteractorInput
{
  func fetchGroceries(request: CountProducts.Something.Request)
}

protocol CountProductsInteractorOutput
{
  func presentFetchedGroceryItems(response: CountProducts.Something.Response)
}

class CountProductsInteractor: CountProductsInteractorInput
{
  var output: CountProductsInteractorOutput!
  var worker: GroceriesWorker!
  
  // MARK: - Business logic
  
  func fetchGroceries(request: CountProducts.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = GroceriesWorker(groceriesStore: GroceriesStaticStore())
    worker.fetchGroceryItems(){ items in
      let response = CountProducts.Something.Response(items: items)
      output.presentFetchedGroceryItems(response: response)
    }
  }
}
