//
//  CountProductsConfigurator.swift
//  Groceries
//
//  Created by Juan Giannuzzo on 2/15/17.
//  Copyright (c) 2017 me. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension CountProductsViewController: CountProductsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension CountProductsInteractor: CountProductsViewControllerOutput
{
}

extension CountProductsPresenter: CountProductsInteractorOutput
{
}

class CountProductsConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = CountProductsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: CountProductsViewController)
  {
    let router = CountProductsRouter()
    router.viewController = viewController
    
    let presenter = CountProductsPresenter()
    presenter.output = viewController
    
    let interactor = CountProductsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
